import Head from "next/head";
import Footer from "./Footer";
import Header from "./Header";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export default function Layout ({ children }) {
    return (
        <>
        <Head>
          <title>Title</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
          <main className={`${inter.className}`}>
            { children }
          </main>
          < Footer/>
        </>
      );
}